### ISSUE TITLE
Parameters for Training with 48k Dataset

### ISSUE THREAD

**Issue by Dahee96** [line/open-universe#6]
Hello, 
I would like to train the Universe++ model with a 48k dataset. Are there any model parameters in universepp_24k.yaml that need to be modified for this purpose, or can I train the model using the current parameters as is?

I will wait for your response. Thank you!

**Comment by fakufaku** [comment]
Hi @Dahee96, the rule of thumb used was to downsample the signal to 100 Hz at the center of the UNet and use 2 channels per kHz. In addition, the number of mel spec filters used as input to the condition model should be modified to make sure to cover every frequencies.
So we had the following parameters for the 16 and 24 kHz models.
```
# 16 kHz model (config/model/default.yaml)
score_model:
  rate_factors: [2, 4, 4, 5]
  n_channels: 32
condition_model:
  n_mels: 80
```
```
# 24 kHz model (config/model/universepp_24k.yaml)
score_model:
  rate_factors: [2, 3, 5, 8]
  n_channels: 48
condition_model:
  n_mels: 128
```

So for a 48 kHz model, you could use
```
score_model:
  rate_factors: [3, 4, 5, 8]
  n_channels: 96
condition_model:
  n_mels: 128 (?)
```
And I'm not too sure about the exact number of mels required to cover everything up to 48 kHz, so please check it.
